Add areAllVariationsSelected subject
vtex-apps/condition-layout pull request #22
Opened 2020-09-28 15:03 UTC by kaisermann

#### What problem is this solving?

Some stores need to display blocks conditionally based on if the user has selected all variations of a product. An example is `dzarm`, that wants to display the shipping simulator field only if the user has selected at least one product color.

#### How to test it?

https://kiwi--dzarm.myvtex.com/blusa-manga-curta-em-malha-de-viscose-6rykldken/p

Look for the shipping simulator after choosing a size variation.

#### Screenshots or example usage:

Using `condition.else`: 
![image](https://user-images.githubusercontent.com/12702016/94449315-55b16f00-0182-11eb-88e4-1296dade06e8.png)

Using `condition.product` with `areAllVariationsSelected is true`:
![image](https://user-images.githubusercontent.com/12702016/94449392-66fa7b80-0182-11eb-99b7-148f69b5d1d6.png)
 

#### Describe alternatives you've considered, if any.

Adding this behavior specifically to the `shipping-simulator` component. However, this wouldn't solve the issue when an adjacent block needs to function in the same way, like the phrase accompanying the shipping simulator in the aforementioned page.

#### Related to / Depends on

https://vtex-dev.atlassian.net/jira/software/projects/SF/boards/105?selectedIssue=SF-385

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/xl3Biy7X0kRlzlQBx4/giphy.gif)

2020-09-28 15:10 UTC, klzns approved these changes

2020-09-28 15:44 UTC, guerreirobeatriz requested changes

2020-09-28 15:44 UTC, guerreirobeatriz commented on docs/README.md
> +| `areAllVariationsSelected` | `value` | `true` if every possible visible variations were selected, otherwise `false`. |
```suggestion
| `areAllVariationsSelected` | `value` | Whether all product variations available on the page were selected by the user (`true`) or not (`false`). | 
```

2020-09-28 15:48 UTC, guerreirobeatriz approved these changes

2020-09-29 18:31 UTC, kaisermann commented on react/Condition.ts
> +  if (!ctxMatch || !localMatch) {
This is important 😁

2020-09-29 18:38 UTC, klzns approved these changes

2020-09-29 18:38 UTC, klzns commented on react/Condition.ts
> +  if (!ctxMatch || !localMatch) {
Any tests to get this scenario?

2020-09-29 19:05 UTC, klzns requested changes

2020-09-29 19:05 UTC, klzns commented on react/__tests__/Condition.test.tsx
> +test('Prevents Condition from rendering if context match is falsy', () => {
I think the test is more about the behaviour than checking the internal structure

```suggestion
test('Prevents Condition from rendering at same time of Else', () => {
```

2020-09-29 20:08 UTC, klzns approved these changes
caprichou!

2020-09-30 13:44 UTC, merged