Feature: Condition Layout Category
vtex-apps/condition-layout pull request #50
Opened 2021-07-22 09:06 UTC by cristian-milea

#### What problem is this solving?

Gives ability to render different frontend blocks depending on the current category or department pages.

#### How to test it?

Different category pages display different components.

[Workspace](https://cristi--bestride.myvtex.com/)

#### Screenshots or example usage:

![code](https://user-images.githubusercontent.com/4988454/126614418-10ca0e31-4573-4c28-908e-0db1c6116cc7.png)

#### Describe alternatives you've considered, if any.

#### Related to / Depends on

`vtex.render-runtime`, which was already included

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/26xBsGN2AtMEt7LtC/giphy.gif)

2021-07-30 14:17 UTC, igorbrasileiro requested changes

2021-07-30 14:17 UTC, igorbrasileiro commented on CHANGELOG.md
> +- `ConditionLayoutCategory` component.
```suggestion
### Added
- `ConditionLayoutCategory` component. 
```

2021-07-30 14:17 UTC, igorbrasileiro commented on react/ConditionLayoutCategory.tsx
> +type Props = {
Change to interfaces, because it is better.
```suggestion
interface Props {
```

2021-07-30 14:17 UTC, igorbrasileiro commented on react/ConditionLayoutCategory.tsx
> +type ContextValues = {
```suggestion
interfaces ContextValues {
```

2021-07-30 14:17 UTC, igorbrasileiro commented on react/ConditionLayoutCategory.tsx
> +type HandlerArguments = {
```suggestion
interfaces HandlerArguments {
```

2021-07-30 14:17 UTC, igorbrasileiro commented on react/ConditionLayoutCategory.tsx
> +const HANDLERS: Handlers<ContextValues, HandlerArguments> = {
What do you think about this suggestion?
```suggestion
const handlersMap: Handlers<ContextValues, HandlerArguments> = {
```

2021-07-30 14:17 UTC, igorbrasileiro commented on react/ConditionLayoutCategory.tsx
> +
```suggestion
```

2021-07-30 14:17 UTC, igorbrasileiro commented on react/ConditionLayoutCategory.tsx
> +    return false;
We have a pattern here, that is, the `happy path` should be on the left as much as possible. So knowing that, what do you think about this suggestion?
```suggestion
    if(values.type !== 'category') {
      return false
    }

    return args.ids.includes(values.id)
```

2021-07-30 14:17 UTC, igorbrasileiro commented on react/ConditionLayoutCategory.tsx
> +    return false;
Also here, is the same suggestion that I left above.
```suggestion
    if(values.type !== 'department') {
      return false
    }

    return args.ids.includes(values.id)
```

2021-08-05 12:10 UTC, cristian-milea commented
@igorbrasileiro , I implemented all your suggestions

2021-08-12 11:29 UTC, vtexdaniel commented
@igorbrasileiro this one as well please!

2021-08-18 09:11 UTC, cristian-milea commented
@victorhmp or @icazevedo can you help with next steps for this PR?

2021-09-10 17:18 UTC, victorhmp approved these changes

2021-09-10 17:18 UTC, victorhmp commented on docs/README.md
> +Possible values for the `condition-layout.category`'s `subject` prop:
```suggestion
Possible values for the `condition-layout.category`'s `subject` prop:

```

2021-11-05 00:10 UTC, cristian-milea commented
@icazevedo, can you help with next steps for this PR?

2021-12-09 12:16 UTC, Luis-eplus commented
Hey @icazevedo, Can You aprove and merge this pull request ? This is a very usefull block.

2022-01-07 18:44 UTC, igorbrasileiro approved these changes

2022-01-17 17:28 UTC, merged