Feature/salesChannel
vtex-apps/condition-layout pull request #66
Opened 2022-10-11 14:45 UTC by germanBonacchi

#### What problem is this solving?

Change condition-layout.binding to be able to have the salesChannel as subject 

#### How to test it?

Link and store-theme with a `vtex.condition-layout@2.x:condition-layout.binding` block with condition like this `
"conditions": [
        {
          "subject": "salesChannel",
          "arguments": {
            "id": "2"
          }
        }
      ],
`
[Workspace](https://conditionalsaleschannel--beautycounterqa.myvtex.com)

#### Screenshots or example usage:

![Captura desde 2022-10-11 11-39-59](https://user-images.githubusercontent.com/55905671/195122242-8b539b6d-2d6c-4385-a7de-01c3ca642470.png)
![Captura desde 2022-10-11 11-16-46](https://user-images.githubusercontent.com/55905671/195122348-e5c2d9c2-d173-482a-af96-2bfbea9fe2ca.png)
![Captura desde 2022-10-11 11-43-58](https://user-images.githubusercontent.com/55905671/195123176-8a22f541-5ca8-47e2-940c-098b1dd85d27.png)
![Captura desde 2022-10-11 11-37-36](https://user-images.githubusercontent.com/55905671/195122367-e7dc75cd-f826-43be-bc1f-55e1d69c9a71.png)

2022-10-11 17:07 UTC, sheilagomes commented
@germanBonacchi , when you need translation/reviews please open a JIRA task for the Product Localization team. I opened [one for this PR](https://vtex-dev.atlassian.net/browse/LOC-9438), but here are the [instructions for opening one](https://www.notion.so/vtexhandbook/Localization-c2491700fcfe4e4e971fb75bf8280498#7baec4cae292436e8d1a08756c66f229) next time.

2022-10-11 17:46 UTC, sheilagomes commented
> @sheilagomes i can't access to the links that you share, i am not from vtex anymore

Oh, ok, no problem! The task is open and the final delivery date is October 21. When it's done, I'll push the corrections to the PR.

2022-10-12 13:45 UTC, germanBonacchi commented
@sheilagomes I can´t use the VTEX IO CI/CD Bot to select a versions, but it needs to be a minor

2022-10-20 14:22 UTC, sheilagomes commented
@germanBonacchi , we need to clarify the term `Sales Channel` used in this app, as sometimes this term is used as equivalent to `Trade Policy` in other apps. What do you mean exactly by sales channel here? Can you give an example of a sales channel, just for us to be sure on the translation?

2022-10-21 00:55 UTC, germanBonacchi commented
Hi @sheilagomes , yes is a confused term sometimes.

I'm talking about `Sales Channel ` equivalent to `Trade Policy`.

For example we have 4 createad here: https://beautycounterqa.myvtex.com/admin/Site/Store.aspx

And if the user is in the sc=1 show some content and if sc=2 show other.

![image](https://user-images.githubusercontent.com/55905671/197086616-4bf7e423-c1ea-43d9-af96-7f553ac3b429.png)

2022-10-21 14:41 UTC, sheilagomes requested changes

2024-08-26 17:44 UTC, closed without merging